### ISSUE TITLE
Chyba při spuštění pluginu

### ISSUE THREAD

**Issue by JirkaSirek** [wombat01/plugin.video.xtv.cz#1]
>ERROR: EXCEPTION Thrown (PythonToCppException) :
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.xtv.cz/addon.py", line 194, in <module>
                                                listShows()
                                              File "/storage/.kodi/addons/plugin.video.xtv.cz/addon.py", line 49, in listShows
                                                addDir('Nejnovější', 'url', '0', '', 2)
                                              File "/storage/.kodi/addons/plugin.video.xtv.cz/addon.py", line 116, in addDir
                                                u = sys.argv[0]+"?url="+urllib.quote_plus(url.encode('utf-8'))+"&id="+urllib.quote_plus(str(id.encode('utf-8')))+"&mode="+str(mode)+"&name="+urllib.quote_plus(name.encode('utf-8'))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)

Systém CoreElec 9.2.3, Kodi 18.7

**Comment by jose1711** [comment]
Podobne aj LibreELEC. Taky fix-nefix (lepsie by bolo asi pouzit `six` modul) je zeditovat `addon.py`:
```
56             name = porad.text
```
zmenit na
```
56             name = porad.text.encode('utf-8')
```

**Comment by JirkaSirek** [comment]
> Podobne aj LibreELEC. Taky fix-nefix (lepsie by bolo asi pouzit `six` modul) je zeditovat `addon.py`:
> 
> ```
> 56             name = porad.text
> ```
> 
> zmenit na
> 
> ```
> 56             name = porad.text.encode('utf-8')
> ```

**Comment by JirkaSirek** [comment]
Tohle moc nepomohlo. Musel jsem upravit na řádku 116

`u = sys.argv[0]+"?url="+urllib.quote_plus(url.encode('utf-8'))+"&id="+urllib.quote_plus(str(id.encode('utf-8')))+"&mode="+str(mode)+"&name="+urllib.quote_plus(name.encode('utf-8'))`

na

`u = sys.argv[0]+"?url="+urllib.quote_plus(url.encode('utf-8'))+"&id="+urllib.quote_plus(str(id.encode('utf-8')))+"&mode="+str(mode)+"&name="+urllib.quote_plus(name)`

**Comment by jose1711** [comment]
ah, spravne.. na toto som zabudol. kazdopadne parsovanie je znova rozbite (tentokrat zmena na strankach)

**Comment by wombat01** [comment]
@JirkaSirek @jose1711 Zkuste v 1.2.0, je to kompletně přepsaný do routingu.

**Comment by JirkaSirek** [comment]
Aktuální verze 1.2.4 vypadá funkčně. Díky.
